<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Model;

use PagePlus\Model\Base\PagePlusProduct as BasePagePlusProduct;

/**
 * Class PagePlusProduct
 * @package PagePlus\Model
 */
class PagePlusProduct extends BasePagePlusProduct
{
}
