<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Model;

use PagePlus\Model\Base\PagePlusI18n as BasePagePlusI18n;

/**
 * Class PagePlusI18n
 * @package PagePlus\Model
 */
class PagePlusI18n extends BasePagePlusI18n
{
}
