<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Model;

use PagePlus\Model\Base\PagePlus as BasePagePlus;

/**
 * Class PagePlus
 * @package PagePlus\Model
 */
class PagePlus extends BasePagePlus
{
}
