<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Action;

use PagePlus\Action\Base\PagePlusProductAction as  BasePagePlusProductAction;

/**
 * Class PagePlusProductAction
 * @package PagePlus\Action
 */
class PagePlusProductAction extends BasePagePlusProductAction
{
}
