<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Action;

use PagePlus\Action\Base\PagePlusAction as  BasePagePlusAction;

/**
 * Class PagePlusAction
 * @package PagePlus\Action
 */
class PagePlusAction extends BasePagePlusAction
{
}
