<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Form\Type;

use PagePlus\Form\Type\Base\PagePlusProductIdType as BasePagePlusProductIdType;

/**
 * Class PagePlusProduct
 * @package PagePlus\Form
 */
class PagePlusProductIdType extends BasePagePlusProductIdType
{
}
