<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Form\Type;

use PagePlus\Form\Type\Base\PagePlusIdType as BasePagePlusIdType;

/**
 * Class PagePlus
 * @package PagePlus\Form
 */
class PagePlusIdType extends BasePagePlusIdType
{
}
