<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Event\Module\Base;

/**
 * Class PagePlusEvents
 * @package PagePlus\Event\Module\Base
 * @author TheliaStudio
 */
class PagePlusEvents
{
    const PAGE_PLUS_CREATE = "action.page_plus.create";
    const PAGE_PLUS_UPDATE = "action.page_plus.update";
    const PAGE_PLUS_DELETE = "action.page_plus.delete";
    const PAGE_PLUS_PRODUCT_CREATE = "action.page_plus_product.create";
    const PAGE_PLUS_PRODUCT_UPDATE = "action.page_plus_product.update";
    const PAGE_PLUS_PRODUCT_DELETE = "action.page_plus_product.delete";
}
