<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Event;

use PagePlus\Event\Base\PagePlusProductEvents as BasePagePlusProductEvents;

/**
 * Class PagePlusProductEvents
 * @package PagePlus\Event
 */
class PagePlusProductEvents extends BasePagePlusProductEvents
{
}
