<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Event;

use PagePlus\Event\Base\PagePlusEvent as BasePagePlusEvent;

/**
 * Class PagePlusEvent
 * @package PagePlus\Event
 */
class PagePlusEvent extends BasePagePlusEvent
{
}
