<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Event;

use PagePlus\Event\Base\PagePlusProductEvent as BasePagePlusProductEvent;

/**
 * Class PagePlusProductEvent
 * @package PagePlus\Event
 */
class PagePlusProductEvent extends BasePagePlusProductEvent
{
}
