<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Event;

use PagePlus\Event\Base\PagePlusEvents as BasePagePlusEvents;

/**
 * Class PagePlusEvents
 * @package PagePlus\Event
 */
class PagePlusEvents extends BasePagePlusEvents
{
}
