<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Form\Base;

use PagePlus\PagePlus;
use Thelia\Form\BaseForm;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class PagePlusCreateForm
 * @package PagePlus\Form\Base
 * @author TheliaStudio
 */
class PagePlusCreateForm extends BaseForm
{
    const FORM_NAME = "page_plus_create";

    public function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addTitleField($translationKeys, $fieldsIdKeys);
        $this->addDescriptionField($translationKeys, $fieldsIdKeys);
        $this->addImageField($translationKeys, $fieldsIdKeys);
        $this->addAltField($translationKeys, $fieldsIdKeys);
        $this->addLocaleField();
    }

    public function addLocaleField()
    {
        $this->formBuilder->add(
            'locale',
            'hidden',
            [
                'constraints' => [ new NotBlank() ],
                'required'    => true,
            ]
        );
    }

    protected function addTitleField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("title", "text", array(
            "label" => $this->translator->trans($this->readKey("title", $translationKeys), [], PagePlus::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("title", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    protected function addDescriptionField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("description", "textarea", array(
            "label" => $this->translator->trans($this->readKey("description", $translationKeys), [], PagePlus::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("description", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    protected function addImageField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("image", "text", array(
            "label" => $this->translator->trans($this->readKey("image", $translationKeys), [], PagePlus::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("image", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    protected function addAltField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("alt", "text", array(
            "label" => $this->translator->trans($this->readKey("alt", $translationKeys), [], PagePlus::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("alt", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "title" => "page_plus_title",
            "description" => "page_plus_description",
            "image" => "page_plus_image",
            "alt" => "page_plus_alt",
        );
    }
}
