<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Form\Base;

use PagePlus\PagePlus;
use Thelia\Form\BaseForm;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * Class PagePlusProductCreateForm
 * @package PagePlus\Form\Base
 * @author TheliaStudio
 */
class PagePlusProductCreateForm extends BaseForm
{
    const FORM_NAME = "page_plus_product_create";

    public function buildForm()
    {
        $translationKeys = $this->getTranslationKeys();
        $fieldsIdKeys = $this->getFieldsIdKeys();

        $this->addProductIdField($translationKeys, $fieldsIdKeys);
        $this->addPagePlusIdField($translationKeys, $fieldsIdKeys);
    }

    protected function addProductIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("product_id", "integer", array(
            "label" => $this->translator->trans($this->readKey("product_id", $translationKeys), [], PagePlus::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("product_id", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    protected function addPagePlusIdField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("page_plus_id", "integer", array(
            "label" => $this->translator->trans($this->readKey("page_plus_id", $translationKeys), [], PagePlus::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("page_plus_id", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }

    public function getName()
    {
        return static::FORM_NAME;
    }

    public function readKey($key, array $keys, $default = '')
    {
        if (isset($keys[$key])) {
            return $keys[$key];
        }

        return $default;
    }

    public function getTranslationKeys()
    {
        return array();
    }

    public function getFieldsIdKeys()
    {
        return array(
            "product_id" => "page_plus_product_product_id",
            "page_plus_id" => "page_plus_product_page_plus_id",
        );
    }
}
