<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Loop;

use PagePlus\Loop\Base\PagePlus as BasePagePlusLoop;

/**
 * Class PagePlus
 * @package PagePlus\Loop
 */
class PagePlus extends BasePagePlusLoop
{
    /**
     * You may now add your own logic
     */
}
