<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Loop;

use PagePlus\Loop\Base\PagePlusProduct as BasePagePlusProductLoop;

/**
 * Class PagePlusProduct
 * @package PagePlus\Loop
 */
class PagePlusProduct extends BasePagePlusProductLoop
{
    /**
     * You may now add your own logic
     */
}
