<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Form;

use PagePlus\Form\Base\PagePlusProductCreateForm as BasePagePlusProductCreateForm;

/**
 * Class PagePlusProductCreateForm
 * @package PagePlus\Form
 */
class PagePlusProductCreateForm extends BasePagePlusProductCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "product_id" => "Product id",
            "page_plus_id" => "Page plus id",
        );
    }
}
