<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Form;

use PagePlus\Form\Base\PagePlusCreateForm as BasePagePlusCreateForm;
use PagePlus\PagePlus;

/**
 * Class PagePlusCreateForm
 * @package PagePlus\Form
 */
class PagePlusCreateForm extends BasePagePlusCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "title" => "Titre",
            "description" => "Description",
            "image" => "Image",
            "alt" => "Décrivez votre image",
        );
    }

    protected function addImageField(array $translationKeys, array $fieldsIdKeys)
    {
        $this->formBuilder->add("image", "file", array(
            "label" => $this->translator->trans($this->readKey("image", $translationKeys), [], PagePlus::MESSAGE_DOMAIN),
            "label_attr" => ["for" => $this->readKey("image", $fieldsIdKeys)],
            "required" => false,
            "constraints" => array(
            ),
            "attr" => array(
            )
        ));
    }
}
