<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Form;

use PagePlus\Form\Base\PagePlusProductUpdateForm as BasePagePlusProductUpdateForm;

/**
 * Class PagePlusProductUpdateForm
 * @package PagePlus\Form
 */
class PagePlusProductUpdateForm extends BasePagePlusProductUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "product_id" => "product_id",
            "page_plus_id" => "page_plus_id",
        );
    }
}
