<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Form;

use PagePlus\Form\Base\PagePlusUpdateForm as BasePagePlusUpdateForm;

/**
 * Class PagePlusUpdateForm
 * @package PagePlus\Form
 */
class PagePlusUpdateForm extends BasePagePlusUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "title" => "title",
            "description" => "description",
            "image" => "image",
            "alt" => "alt",
        );
    }
}
