<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Event\Module;

use PagePlus\Event\Module\Base\PagePlusEvents as BasePagePlusEvents;

/**
 * Class PagePlusEvents
 * @package PagePlus\Event\Module
 * @author TheliaStudio
 */
class PagePlusEvents extends BasePagePlusEvents
{
}
