<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Event\Base;

use Thelia\Core\Event\ActionEvent;
use PagePlus\Model\PagePlusProduct;

/**
* Class PagePlusProductEvent
* @package PagePlus\Event\Base
* @author TheliaStudio
*/
class PagePlusProductEvent extends ActionEvent
{
    protected $id;
    protected $productId;
    protected $pagePlusId;
    protected $pagePlusProduct;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getProductId()
    {
        return $this->productId;
    }

    public function setProductId($productId)
    {
        $this->productId = $productId;

        return $this;
    }

    public function getPagePlusId()
    {
        return $this->pagePlusId;
    }

    public function setPagePlusId($pagePlusId)
    {
        $this->pagePlusId = $pagePlusId;

        return $this;
    }

    public function getPagePlusProduct()
    {
        return $this->pagePlusProduct;
    }

    public function setPagePlusProduct(PagePlusProduct $pagePlusProduct)
    {
        $this->pagePlusProduct = $pagePlusProduct;

        return $this;
    }
}
