<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Event\Base;

use Thelia\Core\Event\ActionEvent;
use PagePlus\Model\PagePlus;

/**
* Class PagePlusEvent
* @package PagePlus\Event\Base
* @author TheliaStudio
*/
class PagePlusEvent extends ActionEvent
{
    protected $id;
    protected $title;
    protected $description;
    protected $image;
    protected $alt;
    protected $pagePlus;
    protected $locale;

    public function getLocale()
    {
        return $this->locale;
    }

    public function setLocale($v)
    {
        $this->locale = $v;

        return $this;
    }

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription()
    {
        return $this->description;
    }

    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    public function getAlt()
    {
        return $this->alt;
    }

    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    public function getPagePlus()
    {
        return $this->pagePlus;
    }

    public function setPagePlus(PagePlus $pagePlus)
    {
        $this->pagePlus = $pagePlus;

        return $this;
    }
}
