<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Controller;

use PagePlus\Controller\Base\PagePlusController as BasePagePlusController;

/**
 * Class PagePlusController
 * @package PagePlus\Controller
 */
class PagePlusController extends BasePagePlusController
{
}
