<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Controller;

use PagePlus\Controller\Base\PagePlusProductController as BasePagePlusProductController;

/**
 * Class PagePlusProductController
 * @package PagePlus\Controller
 */
class PagePlusProductController extends BasePagePlusProductController
{
}
