<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace PagePlus\Action\Base;

use PagePlus\Model\Map\PagePlusProductTableMap;
use PagePlus\Event\PagePlusProductEvent;
use PagePlus\Event\PagePlusProductEvents;
use PagePlus\Model\PagePlusProductQuery;
use PagePlus\Model\PagePlusProduct;
use Thelia\Action\BaseAction;
use Thelia\Core\Event\ToggleVisibilityEvent;
use Thelia\Core\Event\UpdatePositionEvent;
use Propel\Runtime\Propel;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Thelia\Core\Event\TheliaEvents;
use \Thelia\Core\Event\TheliaFormEvent;

/**
 * Class PagePlusProductAction
 * @package PagePlus\Action
 * @author TheliaStudio
 */
class PagePlusProductAction extends BaseAction implements EventSubscriberInterface
{
    public function create(PagePlusProductEvent $event)
    {
        $this->createOrUpdate($event, new PagePlusProduct());
    }

    public function update(PagePlusProductEvent $event)
    {
        $model = $this->getPagePlusProduct($event);

        $this->createOrUpdate($event, $model);
    }

    public function delete(PagePlusProductEvent $event)
    {
        $this->getPagePlusProduct($event)->delete();
    }

    protected function createOrUpdate(PagePlusProductEvent $event, PagePlusProduct $model)
    {
        $con = Propel::getConnection(PagePlusProductTableMap::DATABASE_NAME);
        $con->beginTransaction();

        try {
            if (null !== $id = $event->getId()) {
                $model->setId($id);
            }

            if (null !== $productId = $event->getProductId()) {
                $model->setProductId($productId);
            }

            if (null !== $pagePlusId = $event->getPagePlusId()) {
                $model->setPagePlusId($pagePlusId);
            }

            $model->save($con);

            $con->commit();
        } catch (\Exception $e) {
            $con->rollback();

            throw $e;
        }

        $event->setPagePlusProduct($model);
    }

    protected function getPagePlusProduct(PagePlusProductEvent $event)
    {
        $model = PagePlusProductQuery::create()->findPk($event->getId());

        if (null === $model) {
            throw new \RuntimeException(sprintf(
                "The 'page_plus_product' id '%d' doesn't exist",
                $event->getId()
            ));
        }

        return $model;
    }

    public function beforeCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function beforeUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterCreateFormBuild(TheliaFormEvent $event)
    {
    }

    public function afterUpdateFormBuild(TheliaFormEvent $event)
    {
    }

    /**
     * Returns an array of event names this subscriber wants to listen to.
     *
     * The array keys are event names and the value can be:
     *
     *  * The method name to call (priority defaults to 0)
     *  * An array composed of the method name to call and the priority
     *  * An array of arrays composed of the method names to call and respective
     *    priorities, or 0 if unset
     *
     * For instance:
     *
     *  * array('eventName' => 'methodName')
     *  * array('eventName' => array('methodName', $priority))
     *  * array('eventName' => array(array('methodName1', $priority), array('methodName2'))
     *
     * @return array The event names to listen to
     *
     * @api
     */
    public static function getSubscribedEvents()
    {
        return array(
            PagePlusProductEvents::CREATE => array("create", 128),
            PagePlusProductEvents::UPDATE => array("update", 128),
            PagePlusProductEvents::DELETE => array("delete", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".page_plus_product_create" => array("beforeCreateFormBuild", 128),
            TheliaEvents::FORM_BEFORE_BUILD . ".page_plus_product_update" => array("beforeUpdateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".page_plus_product_create" => array("afterCreateFormBuild", 128),
            TheliaEvents::FORM_AFTER_BUILD . ".page_plus_product_update" => array("afterUpdateFormBuild", 128),
        );
    }
}
